# Generated by Django 4.0.8 on 2024-03-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length='100')),
                ('student_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('index_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('reference_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('level', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=25, null=True)),
            ],
        ),
    ]
