# Generated by Django 4.0.8 on 2024-03-06 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400')], max_length=25, null=True)),
                ('academic_fees', models.FloatField()),
                ('student_fess', models.FloatField()),
                ('exams_fees', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField()),
                ('bank_of_payment', models.TextField(max_length='100', unique=True)),
                ('draft_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('levelBilling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.levelbill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.student')),
            ],
        ),
    ]
