# Generated by Django 4.0.8 on 2024-04-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0006_alter_levelbill_academic_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
