# Generated by Django 4.0.8 on 2024-04-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0007_alter_session_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
